sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t apunia81/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true apunia81/docker-react npm run test
